# DevOps-Lab V1.5

version: '3.9'

networks:
  frontend_net:
    ipam:
      config:
        - subnet: 10.0.0.0/24
  backend_net:
    ipam:
      config:
        - subnet: 10.1.0.0/24
  db_net:
    ipam:
      config:
        - subnet: 10.2.0.0/24
  cicd_net:
    ipam:
      config:
        - subnet: 10.3.0.0/24
  monitoring_net:
    ipam:
      config:
        - subnet: 10.4.0.0/24
  mgmt_net:
    ipam:
      config:
        - subnet: 10.5.0.0/24
  mail_net:
    ipam:
      config:
        - subnet: 10.6.0.0/24
  openvpn_net:
    ipam:
      config:
        - subnet: 10.10.0.0/24

services:
  ### OpenVPN Server

  ### DNS Server (CoreDNS)

  ### Email Server (MailDev for testing)

  ### Management UI
  portainer:
    container_name: portainer
    image: portainer/portainer-docker-extension:2.27.6
    networks:
      mgmt_net:
        ipv4_address: 10.5.0.210
      frontend_net:
        ipv4_address: 10.0.0.210
    expose:
      - "9443"
  #  volumes:
  #    - /var/run/docker.sock:/var/run/docker.sock
  ### Jump Server (SSH enabled Ubuntu)

  ### CI/CD Tools

  ### Monitoring

  ### Web Servers / Frontend (HTTPS reverse proxy to all internal apps)

  ## Nginx container
  webserver:
    container_name: nginx
    image: nginx
    networks:
      backend_net:
        ipv4_address: 10.1.0.10
    ports:
      - 80:8080
      - 443:8443
    command: tail -f /dev/null
  
  ## Tomcat containers
  tomcat-1:
    container_name: tomcat-1
    image: tomcat
    networks:
      backend_net:
        ipv4_address: 10.1.0.21
    command: tail -f /dev/null

  tomcat-2:
    container_name: tomcat-2
    image: tomcat
    networks:
      backend_net:
        ipv4_address: 10.1.0.22
    command: tail -f /dev/null

  ### Databases (Private)

  postgres:
    container_name: postgresql-main
    image: main-db
    networks:
      backend_net:
        ipv4_address: 10.2.0.10

  postgres-drc:
    container_name: postgresql-drc
    image: drc-db
    networks:
      backend_net:
        ipv4_address: 10.2.0.100

  ### Dev Images

  ubuntu:
    container_name: dev1
    image: ubuntu
    networks:
      backend_net:
        ipv4_address: 10.1.0.100
    command: tail -f /dev/null

  alpine:
    container_name: dev2
    image: alpine
    networks:
      backend_net:
        ipv4_address: 10.1.0.101
    command: tail -f /dev/null







